# Generated by Django 4.2.7 on 2025-10-28 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_userprofile_weight_bloodstock"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donation_gap_days", models.PositiveIntegerField(default=90)),
                ("default_search_radius_km", models.PositiveIntegerField(default=10)),
                (
                    "site_contact_email",
                    models.EmailField(default="support@hemovital.com", max_length=254),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donor_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Accepted", "Accepted")],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="bloodstock",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("BLOOD_REQUEST", "New Blood Request"),
                            ("REQUEST_UPDATE", "Request Status Update"),
                            ("BADGE_UNLOCKED", "Badge Unlocked"),
                            ("CAMP_ALERT", "New Blood Camp"),
                            ("SYSTEM_ALERT", "System Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIPredictionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("DONOR_MATCH", "Donor Matching"),
                            ("ELIGIBILITY_PREDICTION", "Eligibility Prediction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("input_data", models.JSONField(null=True)),
                ("output_data", models.JSONField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
