# Generated by Django 4.2.7 on 2025-10-28 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_globalsetting_bloodrequest_donor_bloodrequest_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="donation",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
