# Generated by Django 5.2.7 on 2025-11-05 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donation_created_at_alter_donation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipredictionlog',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='actual_donors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='expected_donors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='fulfillment_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='critical_threshold',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='minimum_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='units_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donation',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='core.bloodrequest'),
        ),
        migrations.AddField(
            model_name='donation',
            name='has_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='ai_prediction_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='analytics_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='chatbot_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='avg_response_time',
            field=models.FloatField(default=0.0, help_text='Average response time in hours'),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='fulfillment_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='total_blood_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability_radius',
            field=models.PositiveIntegerField(default=10, help_text='Availability radius in km'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='engagement_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_completion_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_donations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aipredictionlog',
            name='input_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aipredictionlog',
            name='output_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aipredictionlog',
            name='prediction_type',
            field=models.CharField(choices=[('DONOR_MATCH', 'Donor Matching'), ('ELIGIBILITY_PREDICTION', 'Eligibility Prediction'), ('DEMAND_PREDICTION', 'Demand Prediction'), ('RETENTION_RISK', 'Retention Risk Analysis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BLOOD_REQUEST', 'New Blood Request'), ('REQUEST_UPDATE', 'Request Status Update'), ('BADGE_UNLOCKED', 'Badge Unlocked'), ('CAMP_ALERT', 'New Blood Camp'), ('SYSTEM_ALERT', 'System Alert'), ('STOCK_ALERT', 'Blood Stock Alert')], max_length=50),
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('intent_detected', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_score', models.FloatField(default=0.0)),
                ('response_rate', models.FloatField(default=0.0, help_text='Response rate to blood requests')),
                ('avg_response_time', models.FloatField(default=0.0, help_text='Average response time in hours')),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('total_notifications', models.PositiveIntegerField(default=0)),
                ('notifications_read', models.PositiveIntegerField(default=0)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('retention_risk_score', models.FloatField(default=0.0)),
                ('churn_probability', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('fulfilled_requests', models.PositiveIntegerField(default=0)),
                ('fulfillment_rate', models.FloatField(default=0.0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('total_donors_engaged', models.PositiveIntegerField(default=0)),
                ('donor_satisfaction_score', models.FloatField(default=0.0)),
                ('blood_group_stats', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
