# Generated by Django 5.2.7 on 2025-11-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aipredictionlog_confidence_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='admin_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
